from sqlalchemy import Column, String, Float, Integer

from .database import Base

class Car(Base):
    __tablename__ = "cars"

    url = Column(String, primary_key=True, index=True)
    model = Column(String)
    make = Column(String)
    price = Column(Float)
    year = Column(Integer)
    passenger_doors = Column(Integer)
    passenger_capacity = Column(Integer)
    transmission = Column(String)
    drive_type = Column(String)
    zero_60_mph = Column(String)
    epa_mileage_combined = Column(String)
    horsepower = Column(String)
    torque = Column(String)
    cylinders = Column(String)
    base_engine_size = Column(String)
    engine_type = Column(String)
    front_suspension_type = Column(String)
    rear_suspension_type = Column(String)
    front_brakes = Column(String)
    rear_brakes = Column(String)
    brake_type = Column(String)
    abs_brakes_type = Column(String)
    curb_weight = Column(String)
    fuel_tank_capacity = Column(String)
    dead_weight_hitch___max_tongue_weight = Column(String)
    dead_weight_hitch___max_trailer_weight = Column(String)
    max_trailering_capacity = Column(String)
    weight_distributing_hitch___max_tongue_weight = Column(String)
    weight_distributing_hitch___max_trailer_weight = Column(String)
    length = Column(String)
    width = Column(String)
    height = Column(String)
    wheelbase = Column(String)
    ground_clearance = Column(String)
    turning_circle = Column(String)
    front_head_room = Column(String)
    front_leg_room = Column(String)
    front_shoulder_room = Column(String)
    front_hip_room = Column(String)
    rear_head_room = Column(String)
    rear_leg_room = Column(String)
    rear_shoulder_room = Column(String)
    rear_hip_room = Column(String)
    third_row_head_room = Column(String)
    third_row_leg_room = Column(String)
    third_row_shoulder_room = Column(String)
    third_row_hip_room = Column(String)